env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - FRAMEWORK_NAME=ValidationNEL
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode7.3
      script:
        - pod lib lint
    - os: osx
      language: objective-c
      osx_image: xcode7.3
      before_install:
        - brew update
        - brew outdated carthage || brew upgrade carthage
      before_script:
        # rebuild frameworks if Cartfile.resolved is changed from last build
        - sh bin/bootstrap-if-needed
      script:
        - sh bin/ci
      #after_success:
        #- bash <(curl -s https://codecov.io/bash) -J 'ValidationNEL'
      cache:
        directories:
          - Carthage/Build
      before_deploy:
        - carthage build --no-skip-current
        - carthage archive $FRAMEWORK_NAME
